version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    depends_on:
      - "backend"
    environment:
      - PORT=8001
      - BACKEND_URL=http://backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
