services:
  backend:
    build: 
      context: backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - public

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "8001:8001"
    depends_on:
      - "backend"
    environment:
      - PORT=8001
      - VUE_APP_BACKEND_URL=http://localhost:8000
    networks:
      - public

networks:
  public:
